spring.application.name=NOTIFICATION-SERVICE

server.port=8086

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationservice
spring.datasource.username=postgres
spring.datasource.password=Sesha@2003!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.show-sql=true

spring.main.allow-circular-references=true

eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
eureka.client.instance.preferIpAddress = true
eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true

springdoc.api-docs.path=/swagger-ui


#URLS
service.authentication.name=AUTH-SERVICE
service.authentication.url=http://localhost:8080

service.gateway.name=API-GATEWAY
service.gateway.url=http://localhost:8082


service.order.name=ORDER-SERVICE
service.order.url=http://localhost:8085


service.notification.name=NOTIFICATION-SERVICE
service.notification.url=http://localhost:8086


#KafkaConfuguration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

#spring.datasource.url=jdbc:h2:mem:resturant
#spring.datasource.test.diver-class-name=org.h2.Driver
#spring.datasource.test.username=sa
#spring.datasource.test.password=
#spring.jpa.test.hibernate.ddl-auto = create-drop
